windowrule {
  name = windowrule-3
  workspace = 1
  match:class = brave-browser
}

windowrule {
  name = windowrule-4
  workspace = 2 silent
  match:class = discord
}

windowrule {
  name = windowrule-5
  workspace = 3 silent
  match:class = Spotify
}

windowrule {
  name = windowrule-6
  workspace = 4 silent
  tile = on
  match:class = ^(steam)$
}

windowrule = tile on, match:class steam, match:title Steam
windowrule = tile on, match:class steam, match:title Friends List